In [127]:
import pandas as pd
import numpy as np

## Data Frames

In [128]:
forum_users = {
    'User ID': np.array([1, 2, 3, 4, 5]),
    'Username': ['bogdan_s', 'jane_smith', 'alex123', 'bob56', 'mark_wilson'],
    'Age': [18, 35, 25, 38, None],
    'Joined Date': pd.to_datetime(['2032-01-01', '2032-02-15', '2032-04-25', '2032-06-21', '2032-09-15']),
    'Total Posts': [150, 230, 80, 420, 310],
    'Reputation': [500, 720, 200, 940, 500]
}

df = pd.DataFrame(forum_users)
df

User ID     Username   Age Joined Date  Total Posts  Reputation
0        1     bogdan_s  18.0  2032-01-01          150         500
1        2   jane_smith  35.0  2032-02-15          230         720
2        3      alex123  25.0  2032-04-25           80         200
3        4        bob56  38.0  2032-06-21          420         940
4        5  mark_wilson   NaN  2032-09-15          310         500

In [129]:
df.shape

(5, 6)

In [130]:
type(df)

pandas.core.frame.DataFrame

In [131]:
df.columns

Index(['User ID', 'Username', 'Age', 'Joined Date', 'Total Posts',
       'Reputation'],
      dtype='object')

In [132]:
type(df.columns)

pandas.core.indexes.base.Index

In [133]:
df.columns.tolist()

['User ID', 'Username', 'Age', 'Joined Date', 'Total Posts', 'Reputation']

In [134]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [135]:
df.index.tolist()

[0, 1, 2, 3, 4]

In [136]:
df.dtypes

User ID                 int64
Username               object
Age                   float64
Joined Date    datetime64[ns]
Total Posts             int64
Reputation              int64
dtype: object

In [137]:
df.values

array([[1, 'bogdan_s', 18.0, Timestamp('2032-01-01 00:00:00'), 150, 500],
       [2, 'jane_smith', 35.0, Timestamp('2032-02-15 00:00:00'), 230,
        720],
       [3, 'alex123', 25.0, Timestamp('2032-04-25 00:00:00'), 80, 200],
       [4, 'bob56', 38.0, Timestamp('2032-06-21 00:00:00'), 420, 940],
       [5, 'mark_wilson', nan, Timestamp('2032-09-15 00:00:00'), 310,
        500]], dtype=object)

In [138]:
type(df.values)

numpy.ndarray

In [139]:
df.values[1, 1]

'jane_smith'

In [140]:
df.values.tolist()

[[1, 'bogdan_s', 18.0, Timestamp('2032-01-01 00:00:00'), 150, 500],
 [2, 'jane_smith', 35.0, Timestamp('2032-02-15 00:00:00'), 230, 720],
 [3, 'alex123', 25.0, Timestamp('2032-04-25 00:00:00'), 80, 200],
 [4, 'bob56', 38.0, Timestamp('2032-06-21 00:00:00'), 420, 940],
 [5, 'mark_wilson', nan, Timestamp('2032-09-15 00:00:00'), 310, 500]]

In [141]:
for l in df.values.tolist():
    print(l[1])

bogdan_s
jane_smith
alex123
bob56
mark_wilson


In [142]:
df.head()

User ID     Username   Age Joined Date  Total Posts  Reputation
0        1     bogdan_s  18.0  2032-01-01          150         500
1        2   jane_smith  35.0  2032-02-15          230         720
2        3      alex123  25.0  2032-04-25           80         200
3        4        bob56  38.0  2032-06-21          420         940
4        5  mark_wilson   NaN  2032-09-15          310         500

In [143]:
df.head(3)

User ID    Username   Age Joined Date  Total Posts  Reputation
0        1    bogdan_s  18.0  2032-01-01          150         500
1        2  jane_smith  35.0  2032-02-15          230         720
2        3     alex123  25.0  2032-04-25           80         200

In [144]:
df.tail()

User ID     Username   Age Joined Date  Total Posts  Reputation
0        1     bogdan_s  18.0  2032-01-01          150         500
1        2   jane_smith  35.0  2032-02-15          230         720
2        3      alex123  25.0  2032-04-25           80         200
3        4        bob56  38.0  2032-06-21          420         940
4        5  mark_wilson   NaN  2032-09-15          310         500

In [145]:
df.tail(2)

User ID     Username   Age Joined Date  Total Posts  Reputation
3        4        bob56  38.0  2032-06-21          420         940
4        5  mark_wilson   NaN  2032-09-15          310         500

In [146]:
df.describe()

User ID        Age          Joined Date  Total Posts  Reputation
count  5.000000   4.000000                    5     5.000000    5.000000
mean   3.000000  29.000000  2032-04-28 00:00:00   238.000000  572.000000
min    1.000000  18.000000  2032-01-01 00:00:00    80.000000  200.000000
25%    2.000000  23.250000  2032-02-15 00:00:00   150.000000  500.000000
50%    3.000000  30.000000  2032-04-25 00:00:00   230.000000  500.000000
75%    4.000000  35.750000  2032-06-21 00:00:00   310.000000  720.000000
max    5.000000  38.000000  2032-09-15 00:00:00   420.000000  940.000000
std    1.581139   9.201449                  NaN   133.304163  276.622486

In [147]:
df.describe().round(2)

User ID    Age          Joined Date  Total Posts  Reputation
count     5.00   4.00                    5          5.0        5.00
mean      3.00  29.00  2032-04-28 00:00:00        238.0      572.00
min       1.00  18.00  2032-01-01 00:00:00         80.0      200.00
25%       2.00  23.25  2032-02-15 00:00:00        150.0      500.00
50%       3.00  30.00  2032-04-25 00:00:00        230.0      500.00
75%       4.00  35.75  2032-06-21 00:00:00        310.0      720.00
max       5.00  38.00  2032-09-15 00:00:00        420.0      940.00
std       1.58   9.20                  NaN        133.3      276.62

In [148]:
df.select_dtypes(include='object')

Username
0     bogdan_s
1   jane_smith
2      alex123
3        bob56
4  mark_wilson

In [149]:
df.select_dtypes(include='object').columns

Index(['Username'], dtype='object')

In [150]:
df.select_dtypes(include='int64')

User ID  Total Posts  Reputation
0        1          150         500
1        2          230         720
2        3           80         200
3        4          420         940
4        5          310         500

In [151]:
df.isna()

User ID  Username    Age  Joined Date  Total Posts  Reputation
0    False     False  False        False        False       False
1    False     False  False        False        False       False
2    False     False  False        False        False       False
3    False     False  False        False        False       False
4    False     False   True        False        False       False

In [152]:
df.isna().sum()

User ID        0
Username       0
Age            1
Joined Date    0
Total Posts    0
Reputation     0
dtype: int64

## Series

In [153]:
username_series = df['Username']
username_series

0       bogdan_s
1     jane_smith
2        alex123
3          bob56
4    mark_wilson
Name: Username, dtype: object

In [154]:
type(username_series)

pandas.core.series.Series

In [155]:
username_series.values

array(['bogdan_s', 'jane_smith', 'alex123', 'bob56', 'mark_wilson'],
      dtype=object)

In [156]:
type(username_series.values)

numpy.ndarray

In [157]:
username_series.index

RangeIndex(start=0, stop=5, step=1)

In [158]:
df['Username'].value_counts()

Username
bogdan_s       1
jane_smith     1
alex123        1
bob56          1
mark_wilson    1
Name: count, dtype: int64

In [159]:
df['Username'].value_counts().values

array([1, 1, 1, 1, 1])

In [163]:
df['Reputation'].value_counts()

Reputation
500    2
720    1
200    1
940    1
Name: count, dtype: int64

In [165]:
df['Reputation'].value_counts(ascending=True)

Reputation
720    1
200    1
940    1
500    2
Name: count, dtype: int64

In [164]:
df['Reputation'].value_counts().index

Index([500, 720, 200, 940], dtype='int64', name='Reputation')

In [166]:
df['Reputation'].unique()

array([500, 720, 200, 940])

In [167]:
df['Username'].sort_values()

2        alex123
3          bob56
0       bogdan_s
1     jane_smith
4    mark_wilson
Name: Username, dtype: object

In [168]:
df['Username'].sort_values(ascending=False)

4    mark_wilson
1     jane_smith
0       bogdan_s
3          bob56
2        alex123
Name: Username, dtype: object