In [2]:
import numpy as np

In [3]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
first.shape

(2, 3)

In [5]:
first.ndim

2

In [6]:
second = np.array([[7, 8, 9], [10, 11, 12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [7]:
second.shape

(2, 3)

In [8]:
second.ndim

2

In [9]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [10]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [11]:
first - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [12]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [14]:
second[0,0]

np.int64(7)

In [16]:
second[0]

array([7, 8, 9])

In [18]:
second[1,0]

np.int64(10)

соединение двухмерных массивов по оси 0 дефолтово:

In [19]:
np.concatenate((first, second))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

соединение двухмерных массивов по оси 1:

In [21]:
np.concatenate((first, second), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

соединение одномерных массивов:

In [22]:
np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))

array([1, 2, 3, 4, 5, 6, 7, 8])